name       : python-alembic
version    : 1.0.11
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/a/alembic/alembic-1.0.11.tar.gz : cdb7d98bd5cbf65acd38d70b1c05573c432e6473a82f955cdea541b5c153b0cc
license    : MIT
component  : programming.python
summary    : A database migration tool for SQLAlchemy
description: |
    Alembic is a database migrations tool written by the author of SQLAlchemy.
builddeps  :
    - mako
    - python-dateutil
    - python-editor
    - python-mock
    - python-pytest
    - python-sqlalchemy
rundeps    :
    - mako
    - python-dateutil
    - python-editor
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
