name       : python-alembic
version    : 1.3.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/70/3d/d5ed7a71fe84f9ed0a69e91232a40b0b148b151524dc5bb1c8e4211eb117/alembic-1.3.0.tar.gz : e6c6a4243e89c8d3e2342a1562b2388f3b524c9cac2fccc4d2c461a1320cc1c1
license    : MIT
component  : programming.python
summary    : A database migration tool for SQLAlchemy
description: |
    Alembic is a database migrations tool written by the author of SQLAlchemy.
builddeps  :
    - mako
    - python-dateutil
    - python-editor
    - python-mock
    - python-pytest
    - python-sqlalchemy
rundeps    :
    - mako
    - python-dateutil
    - python-editor
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
