name       : python-alembic
version    : 1.0.10
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/a/alembic/alembic-1.0.10.tar.gz : 828dcaa922155a2b7166c4f36ec45268944e4055c86499bd14319b4c8c0094b7
license    : MIT
component  : programming.python
summary    : A database migration tool for SQLAlchemy
description: |
    Alembic is a database migrations tool written by the author of SQLAlchemy.
builddeps  :
    - mako
    - python-dateutil
    - python-editor
    - python-mock
    - python-pytest
    - python-sqlalchemy
rundeps    :
    - mako
    - python-dateutil
    - python-editor
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
