name       : python-alembic
version    : 1.0.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/1a/37/8df0e37d730f096f5a41514823eaec3c5e169510a5c5ddc3dcbab5446ee8/alembic-1.0.1.tar.gz : 0fe570f23dc48fb1bbda6f6a396f1c0c28d7045c0ad14018c104a511e6c1fe8a
license    : MIT
component  : programming.python
summary    : A database migration tool for SQLAlchemy
description: |
    A database migration tool for SQLAlchemy
builddeps  :
    - python-setuptools
rundeps    :
    - mako
    - python-dateutil
    - python-editor
    - python-sqlalchemy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
