name       : python-alembic
version    : 1.6.5
release    : 9
source     :
    - https://files.pythonhosted.org/packages/2b/cc/5e450e60509b9a68fd761f2fa9ccb6fb9e63d7f9c2b60703bec2e5fd1840/alembic-1.6.5.tar.gz : a21fedebb3fb8f6bbbba51a11114f08c78709377051384c9c5ead5705ee93a51
license    : MIT
component  : programming.python
summary    : A database migration tool for SQLAlchemy
description: |
    Alembic is a database migrations tool written by the author of SQLAlchemy.
builddeps  :
    - mako
    - python-dateutil
    - python-editor
    - python-mock
    - python-pytest
    - python-sqlalchemy
rundeps    :
    - mako
    - python-dateutil
    - python-editor
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
